# Generated by Django 2.2.7 on 2019-12-04 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_mail', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('cus_passwd', models.CharField(max_length=30)),
                ('cus_name', models.CharField(max_length=20)),
                ('cus_addr', models.CharField(max_length=50)),
                ('cus_phone', models.CharField(max_length=20)),
                ('cus_authority', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('st_name', models.CharField(max_length=50)),
                ('st_quantity', models.IntegerField()),
                ('st_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_cname', models.CharField(max_length=20)),
                ('ord_addr', models.CharField(max_length=50)),
                ('ord_phone', models.CharField(max_length=20)),
                ('ord_quantity', models.IntegerField()),
                ('state', models.IntegerField()),
                ('ord_date', models.DateTimeField()),
                ('ord_cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer')),
                ('ord_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='CusAddr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_name', models.CharField(max_length=20)),
                ('ca_addr', models.CharField(max_length=50)),
                ('ca_phone', models.CharField(max_length=20)),
                ('ca_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.Customer')),
            ],
        ),
    ]
